### PR TITLE
 react-menu | extract the style to an external css

### PR DESCRIPTION
**Pull request by yegor-babiy**
Fixes #

## Proposed Changes
- extract styles to avoid issues with multi menus

### CODE REVIEW

**Comment by liorheber** [comment]
@yegor-babiy you didn't use the commit message syntax so the build failed.
Could you issue a new empty PR with a commit message that explains this is a breaking change
e.g. -

BREAKING CHANGE: extract css to an external file

**Comment by yegor-babiy** [comment]
@liorheber 
please take a look
https://github.com/kenshoo/react-menu/pull/56

**Comment by talyak** [comment]
@yegor-babiy , @liorheber - please note [this](https://github.com/kenshoo/react-menu/network/alert/yarn.lock/merge/open) vulnerability alert related to this PR.

**Comment by omerkenshoo** [comment]
@liorheber @yegor-babiy what is this change for?

Can we keep the old style-loader? this really breaks the styling when bumping and I cannot bump

**Pull request merged**
